### ISSUE TITLE
Queries on encrypted data

### ISSUE THREAD

**Issue by elsehow** [feross/peerdb#1]
I know there's been some work on doing queries on encrypted data (when the data is stored on an untrusted host) - was wondering if this is relevant to peerdb's usecases?

refs:
https://eprint.iacr.org/2016/568
https://eprint.iacr.org/2016/591

**Comment by feross** [comment]
Thanks for these links -- this stuff looks really interesting. I'll save the papers and take a look soon.

I think that for now though, PeerDB doesn't need to support advanced queries. It's aiming to just be a dumb key-value store for now. Trustless, encrypted, optimistically P2P.
