### ISSUE TITLE
Arbitrary key?

### ISSUE THREAD

**Issue by sachaservan** [feross/peerdb#2]
What would it take to be able to use an arbitrary key instead of using the torrent's hash? Looking over WebTorrent (particularly torrent.js), it seems like PeerDB could simply announce a given key to the tracker/dht and have that point to the correct "value". Is this a reasonable way of approaching this? The only problem I can see is that there is no way of verifying that the file is "authentic" but if the values are encrypted I don't see why this would be a problem per-se.

**Comment by feross** [comment]
Yeah, you could totally do that using `bittorrent-tracker` directly. This wouldn't work with `webtorrent` though, as it verifies pieces based on the info hash, like you mentioned.
